### ISSUE TITLE
BUG: React-is-not-defined

### ISSUE THREAD

**Issue by leahkatherine** [leahkatherine/nx-app#40]
console error: {"level":50,"time":1705887764930,"pid":13288,"hostname":"LAPTOP-CPFDCM6J","err":{"type":"ReferenceError","message":"React is not defined","stack":"ReferenceError: React is not defined\n    at Object.<anonymous> (C:\\Users\\Leahanestos\\Desktop\\Projects\\react-monorepo\\libs\\web\\design-system\\src\\lib\\components\\icons\\action\\ArrowDownIcon.tsx:4:3)\n    at Module._compile (node:internal/modules/cjs/loader:1356:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)\n    at Module.load (node:internal/modules/cjs/loader:1197:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)\n    at Function.Module._load (C:\\Users\\Leahanestos\\Desktop\\Projects\\react-monorepo\\node_modules\\@nx\\js\\src\\executors\\node\\node-with-require-overrides.js:18:31)\n    at Module.require (node:internal/modules/cjs/loader:1225:19)\n    at require (node:internal/modules/helpers:177:18)\n    at Object.<anonymous> (C:\\Users\\Leahanestos\\Desktop\\Projects\\react-monorepo\\libs\\web\\design-system\\src\\lib\\components\\icons\\action\\index.tsx:2:15)\n    at Module._compile (node:internal/modules/cjs/loader:1356:14)"},"msg":"React is not defined"}

- upon npm start my apps are running parallel. the api  & database has been tested to see if it is working properly and it is. 
TO DO// return back here and document docker terminal messages - Docker Container code running postgres & pgadmin4 
 Next js server not working? You wrote web pack - make sure the custom config is working correctly. also research why front and backened are not interacting, api end point issue, or BUG?

**Comment by leahkatherine** [comment]
Issue is still unresolved. I have updated my web development environment with MAC os. Going to try a few things before I scrap and start over. 
- Look in to testing the server directly to see if its connecting

**Comment by leahkatherine** [comment]
Server is not connecting because of Docker - Need to figure out the docker file for the front end, and test. However, WE need to figure out why backend isn't working to atleast receive calls. Docker issue, or no?
